root: true
env:
  browser: true
  es2020: true

extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:react/recommended'
  - 'plugin:react-hooks/recommended'

parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module

plugins:
  - react
  - react-compiler
  - react-refresh

rules:
  '@typescript-eslint/naming-convention':
    - warn
    - selector: function
      format: [PascalCase, camelCase]
  '@typescript-eslint/no-unused-vars': warn
  '@typescript-eslint/semi': warn
  react-compiler/react-compiler: warn
  react-refresh/only-export-components: warn
  curly: warn
  eqeqeq: warn
  no-empty-pattern: warn
  no-throw-literal: warn
  semi: 'off'

overrides:
  - files: ['*.ts', '*.tsx']
    rules:
      no-undef: 'off'
      react/prop-types: 'off'

settings:
  react:
    version: detect
