name: CI
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 22.x
        uses: actions/setup-node@v3
        with:
          node-version: 22.x

      - name: Build production bundle
        run: npm i
        timeout-minutes: 10

      - name: Build production bundle
        run: npm run build
        timeout-minutes: 10

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: dist
          force_orphan: true
          commit_message: ${{ github.event.head_commit.message }}
